### ISSUE TITLE
Q: Why is the app removed from the iTunes store?

### ISSUE THREAD

**Issue by prusnak** [mycelium-com/wallet-ios#16]
... and when it will come back?

**Comment by redpola** [comment]
Could it be related to https://www.reddit.com/r/Bitcoin/comments/4cfw6t/psa_mycelium_ios_sends_even_when_it_appears/
?

**Comment by prusnak** [comment]
Ah, that might explain this. If that's the case I hope it will be fixed and re-enabled soon. (I don't have an iPhone, but lots of people around me use Mycelium on iOS).

**Comment by Rassah** [comment]
It's because the developer who created it left, while still leaving bugs in it, and we don't have time to fix his problems when we're extremely busy working on a completely new version anyway. The iOS version of our wallet had so few features that there's not much benefit to using ours over other, much better supported options.

**Comment by yegortimoshenko** [comment]
They just closed it, no comments, did you see that?
